### ISSUE TITLE
[Enhancement] Ignore case like toggle word from sublime text.

### ISSUE THREAD

**Issue by jerrykal** [t9md/atom-toggle#4]
@t9md For example, here we have a `toggle` config:
``` cson
'*' [
    ['true', 'false']
]
```
Right now, we can only toggle from `true` to `false`, but the `toggle word` package from sublime text can do from some thing like toggle from `True` to `False` or from `TRUE` to `FALSE`.

**Comment by t9md** [comment]
I can easily enhance it, but unique issue for atom-toggle(this package) is.
- I use this package with `toggle:there` only.
- Wnen `toggle:there`, find the word case-insensitively increase possibility of match.
- This is bad when `toggle:there` unexpectedly toggle word before the word user want to toggle.
  - E.g. `| sample text TRUE or false`, cursor is at `|`, toggle word list is `['true', 'false']`.
    - `toggle:there` toggle `TRUE` to `FALSE` when user want to toggle `false` to `true`.
- I basically want behavior **explicit** to mitigate unwanted toggling.
- In other word want enable case insensitive toggle only specific group of word.

## Workaround

- Define possible pattern, `['True', 'False'], ['TRUE', 'FALSE']`.

## Idea

- Enhance wordlist data structure to allow user control matchability.

```
'*': [
  ['next', 'previous'] # exact only
  { group: ['next', 'previous'], case: ['exact']}
  { group: ['next', 'previous'], case: ['exact', 'opposite']} # next, NEXT
  { group: ['next', 'previous'], case: ['exact', 'opposite', 'title']} # next, NEXT, Next, but not NeXt
]
```

**Comment by t9md** [comment]
More background of my situation

Here is my `toggle.cson` config.
I want toggle `True` to `False` for Haskell source code, but NOT for other text.

```
'*': [
  ['start', 'end']
  ['next', 'previous']
  ['success', 'fail']
  ['increase', 'decrease']
]

'source.coffee': [
  ['horizontal', 'vertical']
  ['forward', 'backward']
  ['before', 'after']
  ['time', 'timeEnd']
]
'source.haskell': [
  ['True'  , 'False']
]
```

**Comment by jerrykal** [comment]
@t9md Thank you for helping, I'll try to consider toggler.
